WebwinkelDJADO/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebwinkelDJADO.Models;

namespace WebwinkelDJADO.Controllers
{
    public class RegisterController : Controller
    {
        private WebwinkelDJADOEntities db = new WebwinkelDJADOEntities();

        public ActionResult Index()
        {
            return View(new Customer()); // return de Index view met een leeg Customer obj
        }

        public RedirectToRouteResult Register(Customer customer) // customer heeft de register form ingevuld we krijgen hier dat ingevuld Customer object binnen
        {
            customer.Password = SHA256.Encode(customer.Password); // encrypteer het paswoord

            db.Customers.Add(customer); // voeg de nieuwe customer toe aan de Customers tabel
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }


    }
}

WebwinkelDJADO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Opdracht 3 Davy Jim</title>
    <script src="http://code.jquery.com/jquery.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WebwinkelDJADO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Shop", "Index", "Shop")</li>
                    <li>@Html.ActionLink("Cart", "Index", "ShoppingCart")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Sign Up", "Index", "Register")</li>
                    <li>@Html.ActionLink("Login", "Index", "Login")</li>                    
                    @if (Request.Cookies["User_type"] != null)
                    {
                        if (Request.Cookies["User_type"].Value == "admin")
                        {
                            <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Opdracht 3 - Davy Jim</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>