WebwinkelDJADO/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebwinkelDJADO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Category Category { get; set; }
    }
}

WebwinkelDJADO/Controllers/ItemDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebwinkelDJADO.Models;

namespace WebwinkelDJADO.Controllers
{
    public class ItemDetailController : Controller
    {
        private WebwinkelDJADOEntities db = new WebwinkelDJADOEntities();

        public ActionResult Index(int id) // parameter is de ProductID van het item (aka product) waarmee we werken, wordt meegegeven via de Html.ActionLink
        {
            var data = db.Products.SingleOrDefault(p => p.ProductID == id); // haalt één product uit de Products table waarvan de ProductID == id. Als het geen vindt return het gwn dat default product, als hij meerdere matches vindt in de tabel geeft het een error
            return View(data); // geef deze als model mee aan de index view
        }
    }
}

WebwinkelDJADO/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebwinkelDJADO.Code.Dal;

namespace WebwinkelDJADO.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            ProductDal dal = new ProductDal();
            ViewBag.Message = "Beheer producten";
            ViewBag.DatabaseMessage = dal.Message;
            return View(dal.ReadAll());
        }

        public ActionResult Inserting()
        {
            ViewBag.Message = "Een postcode inserten";
            return View();
        }

        [HttpPost]
        public ActionResult Insert(Models.Product product)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Message = "Insert een nieuw product in de Products tabel";
                ProductDal dal = new ProductDal(product);
                dal.Create();
                return View("Index", dal.ReadAll());
            }
            else
            {
                ModelState.AddModelError(
                    "Ongeldige gegevens", "Naam van product moet ingevuld zijn.");
                return View("Index");
            }
        }

        [HttpGet]
        // ? zorgt er voor dat een null value geen fout geeft
        public ActionResult Updating(int? id)
        {
            if (id == null)
            {
                ViewBag.Message = "Ongeldige Id";
                return View();
            }
            else
            {
                // lookup product to update
                Models.Product product = new Models.Product();
                // store Product Id
                product.ProductID = (int)id;
                ProductDal dal = new ProductDal(product);
                product = dal.ReadOne();
                ViewBag.Message = "Updating product";
                return View(product); // return de Updating view met een product obj
            }
        }

        [HttpPost]
        // ? zorgt er voor dat een null value geen fout geeft
        public ActionResult Update(Models.Product product)
        {
            if (ModelState.IsValid)
            {
                ProductDal dal = new ProductDal(product);
                dal.Update();
                ViewBag.Message = "Product is geüpdated.";
                return View("Index", dal.ReadAll());
            }
            else
            {
                ModelState.AddModelError("Ongeldige gegevens", "Zie details voor meer uitleg.");
                return View("Index");
            }
        }

        [HttpGet]
        // ? zorgt er voor dat een null value geen fout geeft
        public ActionResult Deleting(int? id)
        {
            if (id == null)
            {
                ViewBag.Message = "Ongeldige Id";
                return View();
            }
            else
            {
                // lookup product to update
                Models.Product product = new Models.Product();
                // store Product Id
                product.ProductID = (int)id;
                ProductDal dal = new ProductDal(product);
                product = dal.ReadOne();
                ViewBag.Message = "Updating product";
                return View(product); // return de Deleting view met een product obj
            }
        }

        [HttpGet]
        // ? zorgt er voor dat een null value geen fout geeft
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                ViewBag.Message = "Ongeldige Id";
                return View("Index");
            }
            else
            {
                // lookup product to update
                Models.Product product = new Models.Product();
                // store Product Id
                product.ProductID = (int)id;
                ProductDal dal = new ProductDal(product);
                dal.Delete();
                ViewBag.Message = "Product deleted";
                return View("Index", dal.ReadAll());
            }
        }

        [HttpGet]
        // ? zorgt er voor dat een null value geen fout geeft
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                ViewBag.Message = "Ongeldige Id";
                return View();
            }
            else
            {
                // lookup product to update
                Models.Product product = new Models.Product();
                // store Product Id
                product.ProductID = (int)id;
                ProductDal dal = new ProductDal(product);
                product = dal.ReadOne();
                ViewBag.Message = "Updating product";
                return View(product); // return de Details view met een product obj
            }
        }
    }
}

WebwinkelDJADO/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebwinkelDJADO.Models;

namespace WebwinkelDJADO.Controllers
{
    public class ShopController : Controller
    {
        private WebwinkelDJADOEntities db = new WebwinkelDJADOEntities();
        private const int PAGE_SIZE = 3; // aantal products per pagina

        public ActionResult Index(int page = 1, int categoryID = 0, string searchString = "") // deze parameter wordt meegegeven via de Html.Actionlink, "= 1" wil zeggen dat dit een optionele parameter is (moet niet worden meegegeven) en als die niet wordt meegeeven is de default page 1. En categoryID = 0 voor de categorie. En searchString = ""
        {
            return View(GetModel(page, categoryID, searchString)); // geef een ProductsModel obj mee aan de index view
        }

        [HttpPost]
        public ActionResult Index(ProductsModel productsModel) // deze wordt gebruikt door de ShopForm in shop index (category dropdown list) wanneer een gebruiker een categorie selecteerd, submit die ShopForm naar deze ActionResult methode.
        {
            int page = 1; // reset de pagina naar de 1ste pagina van die catagorie (als ze op bv de 3 pagina stonden terwijl deze nieuwe categorie kozen worden ze nu terug verwezen naar de 1ste pagina van hun gekozen categorie)
            int categoryID = productsModel.CategoryID; // de gekozen categorie
            return View(GetModel(page, categoryID, productsModel.SearchString));
        }

        private ProductsModel GetModel(int page, int categoryID, string searchString)
        {
            var data = db.Products.Select(p => p)
                        .Where(p => categoryID == 0 || p.CategoryID == categoryID) // haalt alle producten uit de Products table waar de categoryID gelijk is aan 0 of als ze een categorie gekozen hebben, gelijk is aan die categorie.
                        .Where(p => string.IsNullOrEmpty(searchString) || p.Description.Contains(searchString)) // en als geen zoek string is opgegeven hij alle rows returnt, of waar de products description string de zoek string bevat.
                        .OrderBy(p => p.ProductName) // orderd ze adhv ProductName
                        .Skip((page - 1) * PAGE_SIZE).Take(PAGE_SIZE); // skip (sla over) een aantal items, en toon dan de items voor die pagina

            ProductsModel model = new ProductsModel
            {
                Products = data,
                Pagination = new PaginationModel
                {
                    CurrentPage = page,
                    ItemsPerPage = PAGE_SIZE,
                    TotalItems = categoryID == 0 ?
                        db.Products.Count() : // als de user geen categorie heeft gekozen tellen we alle items
                        db.Products.Select(p => p) // als de user wel een categorie heeft gekozen
                        .Where(p => p.CategoryID == categoryID)  // tellen we alle items van die categorie
                        .Where(p => p.Description.Contains(searchString)).Count() // en tellen we alle items waar die zoek string in de description staat.
                },
                CategoryID = categoryID
            };

            return model;
        }
    }
}

WebwinkelDJADO/Views/Shop/Index.cshtml
@model WebwinkelDJADO.Models.ProductsModel

@{
    ViewBag.Title = "ISkills Shop";
}

<h2>Shop</h2>

@using (Html.BeginForm("Index", "Shop", FormMethod.Post, new { id = "ShopForm" }))  // deze form als hij wordt gesubmit, stuurt deze request naar de Index ActionResult methode van de ShopController, via de POST methode, en we zetten de html id naam van deze form naar "ShopForm", zodat de javascript "onchange" event deze kan terugviden.
{
    // verborgen form waarden die worden meegestuurd in de submit request naar de Index ActionResult methode van de ShopController
    @Html.HiddenFor(x => x.Pagination.CurrentPage);
    @Html.HiddenFor(x => x.Pagination.ItemsPerPage);
    @Html.HiddenFor(x => x.Pagination.TotalItems);

    <div class="well">
        <div>
            Category:
            @Html.DropDownListFor(x => x.CategoryID, Model.Categories(), "---Select a Category---",
             new
             {
                 // javascript "onchange" event, als een nieuwe categorie in deze dropdownlist wordt geselecteerd door de gebruiker, gaan we deze shopform automatisch submitten, zodat het de products lijst update naar de gekozen categorie.
                 onchange = "document.getElementById('ShopForm').submit();"
             })
            <span class="pull-right">
                <span class="glyphicon glyphicon-search"></span>
                @Html.TextBoxFor(x => x.SearchString) <!-- de zoekterm die wordt meegegevn in de post request -->
                <input type="submit" value="Search" /> <!-- ook deze subimit onze "ShopForm" --> 
            </span>
        </div>
    </div>

    foreach (var item in Model.Products) // lijst met alle producten
    {
        @Html.Partial("Product", item)
    }

    <div class="pager"> <!-- paginatie links -->
        @Html.PageLinks(Model.Pagination, x => Url.Action("Index", new { page = x, categoryID = Model.CategoryID }))
    </div>
}

WebwinkelDJADO/Views/Shop/Product.cshtml
@model WebwinkelDJADO.Models.Product
<!-- Partial view voor de product list foreach loop in Shop Index view -->
<div style="display: inline-block" class="well">
    <div style="width:30%; float: left;">
        <img src="@Url.Content(@Model.Image)" width="170" height="276" alt="@Model.ProductName" title="@Model.ProductName" />
    </div>
    <div style="width:70%; float: left;">
        <h3>
            @Html.DisplayFor(modelItem => Model.ProductName)
        </h3>
        <p>
            @Html.DisplayFor(modelItem => Model.Description)
        </p>
        <h4>
            <span class="label label-info">
                €@Html.DisplayFor(modelItem => Model.Price)
            </span>
        </h4>
        <p>
            @Html.ActionLink("More Info", "Index", "ItemDetail", new { id = Model.ProductID }, new { id = "ProductID" }) <!-- geeft de ProductID van dit item mee aan de Index Actionresult methode van de ItemDetailController, en de css styling voor deze link komt van id = "ProductID" css class -->
            <!-- @Html.ActionLink("More Info", "Info", new { id = Model.ProductID })  geeft de ProductID van dit item mee aan de Info Actionresult methode van de ShopController -->
        </p>
    </div>
</div>