WebwinkelDJADO/Models/BillingInfo.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Linq;

namespace WebwinkelDJADO.Models
{
    public class BillingInfo
    {
        [Required(ErrorMessage = "Please enter a first name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter a last name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter a credit card number")]
        public string CreditCardNumber { get; set; }

        [Required(ErrorMessage = "Please enter an address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Please enter a city name")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please enter a state name")]
        public string State { get; set; }

        [Required(ErrorMessage = "Please enter a zip code")]
        public string Zip { get; set; }

        [Required(ErrorMessage = "Please enter an expiration date")]
        [DataType(DataType.Text)]
        public string ExpirationMonth { get; set; }

        public SelectList Months()
        {
            return new SelectList(new string[] { "January", "February", "March",
                "April", "May", "June", "July", "August", "September", "October",
                "November", "December" });
        }

        [Required(ErrorMessage = "Please enter an expiration date")]
        [DataType(DataType.Text)]
        public string ExpirationYear { get; set; }

        public SelectList Years()
        {
            return new SelectList(new string[] { "2014", "2015", "2016",
                "2017", "2018", "2019", "2020", "2021", "2022", "2023",
                "2024", "2025" });
        }

    }
}

WebwinkelDJADO/Models/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebwinkelDJADO.Models
{
    public class ShoppingCartViewModel
    {
        public ShoppingCartModel Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebwinkelDJADO/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebwinkelDJADO.Models;

namespace WebwinkelDJADO.Controllers
{

    public class ShoppingCartController : Controller
    {
        private WebwinkelDJADOEntities db = new WebwinkelDJADOEntities();

        public ShoppingCartController()
        {
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new ShoppingCartViewModel
            {
                Cart = GetCart(),
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(int productID, string returnUrl)
        {
            Product product = db.Products.SingleOrDefault(p => p.ProductID == productID);

            if (product != null)
            {
                GetCart().AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(int productId, string returnUrl)
        {
            GetCart().RemoveItem(productId);
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult CartWidget(ShoppingCartModel cart)
        {
            return PartialView(cart);
        }

        private ShoppingCartModel GetCart()
        {
            ShoppingCartModel cart = (ShoppingCartModel)Session["Cart"];
            if (cart == null)
            {
                cart = new ShoppingCartModel();
                Session["Cart"] = cart;
            }
            return cart;
        }

        [Authorize]
        public ViewResult ShippingInfo()
        {
            return View(new ShippingInfo());
        }

        [Authorize]
        [HttpPost]
        public ActionResult ShippingInfo(ShippingInfo shippingInfo)
        {
            if (ModelState.IsValid)
            {
                ShoppingCartModel cart = GetCart();
                cart.ShippingInfo = shippingInfo;
                return RedirectToAction("BillingInfo");
            }
            else
            {
                return View(shippingInfo);
            }
        }

        [Authorize]
        public ViewResult BillingInfo()
        {
            return View(new BillingInfo());
        }

        [Authorize]
        [HttpPost]
        public ViewResult BillingInfo(BillingInfo billingInfo)
        {
            if (ModelState.IsValid)
            {
                ShoppingCartModel cart = GetCart();
                cart.BillingInfo = billingInfo;
                ProcessOrder(cart);
                cart.Clear();
                return View("OrderComplete");
            }
            else
            {
                return View(billingInfo);
            }
        }

        private void ProcessOrder(ShoppingCartModel cart)
        {
            string idString = System.Web.HttpContext.Current.User.Identity.Name;
            int customerID = int.Parse(idString);

            Customer customer = db.Customers.SingleOrDefault(c => c.CustomerID == customerID);
            customer.FirstName = cart.BillingInfo.FirstName;
            customer.LastName = cart.BillingInfo.LastName;
            customer.BillingAddress = cart.BillingInfo.Address;
            customer.BillingCity = cart.BillingInfo.City;
            customer.BillingState = cart.BillingInfo.State;
            customer.BillingPostalCode = cart.BillingInfo.Zip;
            customer.CardNumber = cart.BillingInfo.CreditCardNumber;
            customer.ExpirationMonth = cart.BillingInfo.ExpirationMonth;
            customer.ExpirationYear = cart.BillingInfo.ExpirationYear;

            db.SaveChanges();

            Order order = new Order
            {
                CustomerID = customer.CustomerID,
                OderDate = DateTime.Now,
                ShippingAdress = cart.ShippingInfo.Address,
                ShippingCity = cart.ShippingInfo.City,
                ShippingState = cart.ShippingInfo.State,
                ShippingPostalCode = cart.ShippingInfo.Zip
            };
            db.Orders.Add(order);
            db.SaveChanges();

            foreach (ShoppingCartItemModel item in cart.Items)
            {
                OrderItem orderItem = new OrderItem
                {
                    OrderID = order.OrderID,
                    ProductID = item.Product.ProductID,
                    Quantity = item.Quantity
                };
                db.OrderItems.Add(orderItem);
            }
            db.SaveChanges();
        }
    }
}

WebwinkelDJADO/Views/ShoppingCart/BillingInfo.cshtml
@model WebwinkelDJADO.Models.BillingInfo

@{
    ViewBag.Title = "Billing Information";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <h3>Bill to:</h3>
    <div class="form-group">
        <label>First Name</label>
        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
        <label>Last Name</label>
        @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Credit Card Number</label>
        @Html.TextBoxFor(x => x.CreditCardNumber, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Expiration Date</label>
        @Html.DropDownListFor(x => x.ExpirationMonth, Model.Months(), "--Expiration Month--", new { @class = "form-control" })
        @Html.DropDownListFor(x => x.ExpirationYear, Model.Years(), "--Expiration Year--", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Address</label>
        @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>City</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>State</label>
        @Html.TextBoxFor(x => x.State, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Zip Code</label>
        @Html.TextBoxFor(x => x.Zip, new { @class = "form-control" })
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Checkout" />
    </div>
}

WebwinkelDJADO/Views/ShoppingCart/CartWidget.cshtml
@model WebwinkelDJADO.Models.ShoppingCartModel

<div class="navbar-right" style="margin-left:7px">
    @Html.ActionLink("Checkout", "Index", "Cart",
        new { returnUrl = Request.Url.PathAndQuery },
        new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Cart:</b>
    @Model.Items.Sum(x => x.Quantity) item(s),
    @Model.GetCartTotal().ToString("c")
</div>

WebwinkelDJADO/Views/ShoppingCart/Index.cshtml
@model WebwinkelDJADO.Models.ShoppingCartViewModel
@{
    ViewBag.Title = "WebwinkelDJADO Shopping Cart";
}

<h2>
    <span class="glyphicon glyphicon-shopping-cart"></span>
    Shopping Cart
</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>
                Quantity
            </th>
            <th>
                Item
            </th>
            <th class="text-right">
                Price
            </th>
            <th class="text-right">
                Subtotal
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cart.Items)
        {
            <tr>
                <td class="text-center">
                    @item.Quantity
                </td>
                <td class="text-left">
                    @item.Product.ProductName
                </td>
                <td class="text-right">
                    @item.Product.Price.ToString("c")
                </td>
                <td class="text-right">
                    @((item.Quantity * item.Product.Price).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "ShoppingCart"))
                    {
                        @Html.Hidden("ProductId", item.Product.ProductID)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning"
                               type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">
                Total:
            </td>
            <td class="text-right">
                @Model.Cart.GetCartTotal().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">
        Continue Shopping
    </a>
    @Html.ActionLink("Checkout", "ShippingInfo", null, new { @class = "btn btn-primary" })
</div>

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

WebwinkelDJADO/Views/ShoppingCart/OrderComplete.cshtml
@{
    ViewBag.Title = "Order Accepted";
}

<h2>Thanks!</h2>
Thank you for your order! We'll get right on it!

WebwinkelDJADO/Views/ShoppingCart/ShippingInfo.cshtml
@model WebwinkelDJADO.Models.ShippingInfo

@{
    ViewBag.Title = "Shipping Information";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <h3>Ship to:</h3>
    <div class="form-group">
        <label>Address</label>
        @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>City</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>State</label>
        @Html.TextBoxFor(x => x.State, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Zip Code</label>
        @Html.TextBoxFor(x => x.Zip, new { @class = "form-control" })
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Next" />
    </div>
}